stages:
    - test
    - secret-detection

sast:
    stage: test

include:
    - template: Security/SAST.gitlab-ci.yml
    - template: Security/Secret-Detection.gitlab-ci.yml

variables:
    SECRET_DETECTION_ENABLED: "true"
    SECURE_LOG_LEVEL: "debug"

secret_detection:
    stage: secret-detection
